import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import TankStackProvider from "@/components/providers/TanStackProvider";



export const metadata: Metadata = {
  title: "Abhigram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <ThemeProvider  attribute="class" defaultTheme="system"  enableSystem disableTransitionOnChange>
           <TankStackProvider>
            {children}
           </TankStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
